<a href="https://colab.research.google.com/github/ivannarch865/ivannarichards5to/blob/main/AustralianWines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
file_path="https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/AustralianWines.csv"
import pandas as pd
df= pd.read_csv(file_path)
df.head()

    Month Fortified  Red  Rose   sparkling   Sweet white  Dry white
0  Jan-80      2585   464   112      1686.0         85.0     1954.0
1  Feb-80      3368   675   118      1591.0         89.0     2302.0
2  Mar-80      3210   703   129      2304.0        109.0     3054.0
3  Apr-80      3111   887    99      1712.0         95.0     2414.0
4  May-80      3756  1139   116      1471.0         91.0     2226.0

In [ ]:
df.shape

(188, 7)

In [ ]:
print("Australian Wines has", df.shape[0], "rows")
print("Australian Wines has", df.shape[1], "columns")

Australian Wines has 188 rows
Australian Wines has 7 columns

In [ ]:
df.columns

Index(['Month', 'Fortified', 'Red ', 'Rose ', 'sparkling ', 'Sweet white',
       'Dry white'],
      dtype='object')

In [ ]:
favs=[2,3,4]

In [ ]:
df.iloc[10:20, favs]

    Red  Rose   sparkling
10   996   150      4087.0
11   960   267      5179.0
12   530   126      1530.0
13   883   129      1523.0
14   894   124      1633.0
15  1045    97      1976.0
16  1199   102      1170.0
17  1287   127      1480.0
18  1565   222      1781.0
19  1577   214      2472.0