<a href="https://colab.research.google.com/github/ivannarch865/ivannarichards5to/blob/main/class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Reading files from Public Github repository**

In [ ]:
path1="https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/AccidentsFull.csv"

In [ ]:
import pandas as pd
df1=pd.read_csv(path1)
df1.head()

,HOUR_I_R,ALCHL_I,ALIGN_I,STRATUM_R,WRK_ZONE,WKDY_I_R,INT_HWY,LGTCON_I_R,MANCOL_I_R,PED_ACC_R,...,SUR_COND,TRAF_CON_R,TRAF_WAY,VEH_INVL,WEATHER_R,INJURY_CRASH,NO_INJ_I,PRPTYDMG_CRASH,FATALITIES,MAX_SEV_IR
0,0,2,2,1,0,1,0,3,0,0,...,4,0,3,1,1,1,1,0,0,1
1,1,2,1,0,0,1,1,3,2,0,...,4,0,3,2,2,0,0,1,0,0
2,1,2,1,0,0,1,0,3,2,0,...,4,1,2,2,2,0,0,1,0,0
3,1,2,1,1,0,0,0,3,2,0,...,4,1,2,2,1,0,0,1,0,0
4,1,1,1,0,0,1,0,3,2,0,...,4,0,2,3,1,0,0,1,0,0

In [ ]:
path2='https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/AustralianWines.csv'

In [ ]:
import pandas as pd
df2=pd.read_csv(path2)
df2.head()

    Month Fortified  Red  Rose   sparkling   Sweet white  Dry white
0  Jan-80      2585   464   112      1686.0         85.0     1954.0
1  Feb-80      3368   675   118      1591.0         89.0     2302.0
2  Mar-80      3210   703   129      2304.0        109.0     3054.0
3  Apr-80      3111   887    99      1712.0         95.0     2414.0
4  May-80      3756  1139   116      1471.0         91.0     2226.0

#**2. Read a file from `Private` Github repository**

In [ ]:
path ="https://raw.githubusercontent.com/ivannarch865/ivannarichards5to/refs/heads/main/AccidentsFull.csv?token=GHSAT0AAAAAAEJ43JXEZHYKANDGLQ34FS5K2VTDSBA"
import pandas as pd
df=pd.read_csv(path)
df.head()

,HOUR_I_R,ALCHL_I,ALIGN_I,STRATUM_R,WRK_ZONE,WKDY_I_R,INT_HWY,LGTCON_I_R,MANCOL_I_R,PED_ACC_R,...,SUR_COND,TRAF_CON_R,TRAF_WAY,VEH_INVL,WEATHER_R,INJURY_CRASH,NO_INJ_I,PRPTYDMG_CRASH,FATALITIES,MAX_SEV_IR
0,0,2,2,1,0,1,0,3,0,0,...,4,0,3,1,1,1,1,0,0,1
1,1,2,1,0,0,1,1,3,2,0,...,4,0,3,2,2,0,0,1,0,0
2,1,2,1,0,0,1,0,3,2,0,...,4,1,2,2,2,0,0,1,0,0
3,1,2,1,1,0,0,0,3,2,0,...,4,1,2,2,1,0,0,1,0,0
4,1,1,1,0,0,1,0,3,2,0,...,4,0,2,3,1,0,0,1,0,0

In [ ]:
path4="/content/drive/MyDrive/datasets_testing/births.csv"
df4=pd.read_csv(path4)
df4.head()

   year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

##Some basics -data types

In [ ]:
x=2
type(x)

int

In [ ]:
x1=2.0
type(x1)

float

In [ ]:
x2=0.4/2
type(x2)

float

In [ ]:
0.2+0.3

0.5

In [ ]:
x=None
type(x)

NoneType

###1. Discrete quantitative variables

In [ ]:
rooms=3
type(rooms)

int

In [ ]:
room=[3,4,5]
type(room)

list

In [ ]:
y=-3
type(y)

int

##2. Continous quantitative variables

In [ ]:
y1=3/5
type(y1)

float

In [ ]:
import math

In [ ]:
y2='math.pi'
type(y2)

str

In [ ]:
y3=math.pi
type(y3)

float

In [ ]:
numbers=[1,2,3,4,5]
type(numbers)

list

In [ ]:
some_list =(1,2,3,4,5)
type(some_list)

tuple

In [ ]:
numbers[0]

1

In [ ]:
numbers[0]=100
numbers

[100, 2, 3, 4, 5]